version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run:
          name: Install Playwright Browsers
          command: npx playwright install
      - run:
          name: Run All Playwright Tests
          command: |
            mkdir test-results
            TESTFILES=$(circleci tests glob "specs/e2e/**/*.spec.ts")
            echo "$TESTFILES" | circleci tests run --command="xargs pnpm playwright test --config=playwright.config.ci.ts --reporter=junit" --verbose --split-by=timings
      - store_test_results:
          path: test-results
